### ISSUE TITLE
Confused with SystemDatabaseCredential

### ISSUE THREAD

**Issue by imtrobin** [ra0o0f/arangoclient.net#119]
Hi, I'm abit confused with what SystemDatabaseCredential is for, I did some testing, some functions like CreateDatabaseAsync needs it , while others like ListAccessibleDatabasesAsync needs Credential. Is there a doc or something we can reference?

**Comment by ra0o0f** [comment]
@imtrobin operations like `CreateDatabase` needs system privilege. these operation use `SystemDatabaseCredential` and other use `DatabaseCredential`. i separate credentials so end-users can set limited-access-user (not root) for regular operations.

**Comment by imtrobin** [comment]
Yes, I assume so. Is there a list we can check? Cos it seems insert a document also needs SystemDatabaseCredential, which I found it odd.

**Comment by ra0o0f** [comment]
@imtrobin note that when `SystemDatabaseCredential` is used, all request will be use `_system`, so inserting document should not use `SystemDatabaseCredential`, if it is, its a bug

**Comment by imtrobin** [comment]
I did some more testing. I confirm

1. Creating database needs SystemCredential
2. Creating collection do not need SystemCredential, just Credential
3. Creating doc do not need SystemCredential, just Credential, with user that has permission Administrate.

Is that correct?
