### ISSUE TITLE
Custom Index

### ISSUE THREAD

**Issue by imtrobin** [ra0o0f/arangoclient.net#120]
Hi, is there a way to support custom index instead of _key? In more advanced cases, e.g for creating an authentication system using email, I would not be using the email as the key as I would allow the user to change email in future.

I can create an skiplist index on Email, so I can pass that in, but in the current form, just supporting _key, it means I have to do a search in db to get the _key first.

**Comment by imtrobin** [comment]
I don't think I can use either alternative, because the _key must be immutable. For example, the email can be changed so then, that would change the _key too on hash if its bult from attributes. So I would still have to lookup the db to find the _key from the email.

**Comment by ra0o0f** [comment]
`_key` is immutable and cant be changed after document is created, why `unique hash index` wont work for you? 
```javascript
{
  "_key":"3412342",
  // unique hash index on email attribute
  "email":"some@mail.com"
}
```

**Comment by imtrobin** [comment]
It will work, but as an example, I have to get the _key first. E.g to update a user, the user is gonna pass me his email username, not _key, so I will need to 

 - get _key by searching username email and build Person
- var p = db.Update <Person>
 -

**Comment by imtrobin** [comment]
I did it with an index using ByExample. The examples still requires the key.
