### ISSUE TITLE
Question: How do you query/traverse graphs?

### ISSUE THREAD

**Issue by JulianMay** [ra0o0f/arangoclient.net#16]
Hey

I'm trying to write a query for an assertion for the simplest possible relation:

"target" --[isPartOf]-->"target"

, with the ability of a "target" to be part of 0-* other targets

I've got the insertion of document/nodes right (and asserted with query) - how would you (in psudocode) write the query that Asserts the relation exists?

The model so far looks like this:

```csharp
    public class Target
    {
        [DocumentProperty(Identifier = IdentifierType.Key)]
        public string Key;

        //Is this part of the solution?
        //[DocumentProperty(Identifier = IdentifierType.EdgeTo)]
        ///public string[] IsPartOf;

        public string EntityType;
        public string AggregateId;
    }

    public class IsPartOf
    {
        //What would go here? Nothing?
    }
```

Looking at the ArangoDB.Client.Test, "Product" has a "Category" property, which reminds me of an EF navigationProperty, but I can't seem to find code or documentation about how to go around this...

Any hints or tips are much appreciated :)

/Julian

**Comment by ra0o0f** [comment]
@JulianMay if you want to know your options to how model your data and its relations in ArangoDB, there is a blog post by them in detail with samples

http://radar.oreilly.com/2015/07/data-modeling-with-multi-model-databases.html

but for a simple answer:

```csharp
public class Target
    {
        [DocumentProperty(Identifier = IdentifierType.Key)]
        public string Key;

        [DocumentProperty(Identifier = IdentifierType.Handle)]
        public string Id;

        public string Content;
    }

    public class TargetRelation
    {
        [DocumentProperty(Identifier = IdentifierType.Key)]
        public string Key;

        [DocumentProperty(Identifier = IdentifierType.EdgeFrom)]
        public string From;

        [DocumentProperty(Identifier = IdentifierType.EdgeTo)]
        public string To;
    }                


                var firstTarget = new Target { Content = "firstTarget" };
                var secondTarget = new Target { Content = "secondTarget" };
                var thirdTarget = new Target { Content = "thirdTarget" };

                db.Insert<Target>(firstTarget);
                db.Insert<Target>(secondTarget);
                db.Insert<Target>(thirdTarget);

                TargetRelation relationWithSecond = new TargetRelation();
                db.InsertEdge<TargetRelation>(firstTarget.Id, secondTarget.Id, relationWithSecond);

                TargetRelation relationWithThird = new TargetRelation();
                db.InsertEdge<TargetRelation>(firstTarget.Id, thirdTarget.Id, relationWithThird);


                var relations = db.Edges<TargetRelation>(firstTarget.Id, EdgeDirection.Outbound);

                var count = relations.Select(r => r.To).Except(new string[] { secondTarget.Id, thirdTarget.Id }).Count();

                Debug.Assert(count == 0);
```

also client now does not support ArangoDB `General Graph` operations for now, it will be in the client by tommarow

**Comment by ra0o0f** [comment]
@JulianMay you can also use LINQ(aql query) for this

```csharp
var relationsCount = db.Query()
                    .For(_ => AQL.Edges<TargetRelation>(firstTarget.Id, EdgeDirection.Outbound)
                    .Where(r => AQL.In(r.To, new string[] { secondTarget.Id, thirdTarget.Id })))
                    .Count();

                // which translates to:
                // return length ((
                // for `r` in  edges(  `TargetRelation` , "Target/7433562403", 'outbound')
                // filter  `r`.`_to`  in  ["Target/7433759011", "Target/7433955619"]
                // return  `r` ))

                Debug.Assert(relationsCount == 2);
```

**Comment by JulianMay** [comment]
Thank you so much! 

Just a note: wouldnt you be writing an evergreen here? (Empty result would assert as well as expected result)
```
var count = relations.Select(r => r.To).Except(new string[] { secondTarget.Id, thirdTarget.Id }).Count();
Debug.Assert(count == 0);
```

**Comment by ra0o0f** [comment]
@JulianMay you are right switch the comparison, i said to myself you would debug it to see how it works

**Comment by JulianMay** [comment]
Works like a charm - thanks again

**Comment by JulianMay** [comment]
Just for my understanding: Is is correctly understood that the following traversal problem will be solvable with arrangoclient.net once the general graph operations are implemented?

With this model:
```
"targetB" --[isPartOf]-->"targetA"
"targetC" --[isPartOf]-->"targetB"
"note1" --[attachedTo]-->"targetB"
"note2" --[attachedTo]-->"targetA"
"note3" --[attachedTo]-->"targetC"
```
I'll be able to traverse the graph from "targetA" and return all 3 notes

**Comment by ra0o0f** [comment]
@JulianMay you could do this with this version, without need for creating graph with `General graph` api

```csharp
var firstTarget = new Target { Content = "firstTarget" };
                var secondTarget = new Target { Content = "secondTarget" };
                var thirdTarget = new Target { Content = "thirdTarget" };

                db.Insert<Target>(firstTarget);
                db.Insert<Target>(secondTarget);
                db.Insert<Target>(thirdTarget);

                TargetRelation firstWithSecond = new TargetRelation();
                db.InsertEdge<TargetRelation>(firstTarget.Id, secondTarget.Id, firstWithSecond);

                TargetRelation secondWithThird = new TargetRelation();
                db.InsertEdge<TargetRelation>(secondTarget.Id, thirdTarget.Id, secondWithThird);


                var vertexes = db.Query()
                    .For(_ => AQL.Traversal<Target, TargetRelation>(firstTarget.Id, EdgeDirection.Outbound))
                    .ToList();
```

look at the traversal api ()

https://docs.arangodb.com/Aql/GraphFunctions.html

as far as i know `General graphs` let you define a graph across several edge collections and guarantees like removing vertex and its connected edges transitionally. 

i did not dig deep in to `General graphs` to know where to create graph or not. how about ask it on stackoverflow to get best answer? tag it with `.net` so i can write how to do it in .net client

**Comment by ra0o0f** [comment]
also note that for graph operations and general graph operations, i am working to support all operations and release a new version in incoming days.

**Comment by JulianMay** [comment]
Thanks again - This is awesome

**Comment by ra0o0f** [comment]
@JulianMay client now supports all graph operations

**Comment by JulianMay** [comment]
Awesome :)
