### ISSUE TITLE
Documentation for existing API

### ISSUE THREAD

**Issue by swarnabh1990** [ra0o0f/arangoclient.net#17]
Hi @ra0o0f ,
Is there any proper documentation available that demonstrates how to use this client. I am more interested in using this client than the others because of the Async API and this Client looks really neat. But at the moment I am just not able to get this to work. On the website there is just a general implementation but that is not the case in most real world projects.

It would be really helpful if we have some docs that shows the usage of the various attributes and how to use the models with the client functions etc. This would help people to get started and upgrade as new versions roll out.

Thanks

**Comment by ra0o0f** [comment]
hi @swarnabh1990 

thanks for using the client. i know without the proper documentation, client would not be useful for many people and i'm planning to make a good one with detailed explanation, thats why i build the site [arangoclient.net](http://www.arangoclient.net), but for now i'm busy with my job and i cant do that until two month later.

BUT in a near future(this week) i want to provide samples for all API's and LINQ queries with a little documentation. until then you can open an issue here or ask on stackoverflow, i am usually around and i will answer them asap.

thanks

**Comment by swarnabh1990** [comment]
Hi @ra0o0f ,

Thanks for the quick response. I really appreciate your help. I will check the samples and try to get things done :+1:

**Comment by ra0o0f** [comment]
@swarnabh1990 i start to add examples for the client, examples are in a separate project `ArangoDB.Client.Examples`, each example will be in separate test method and i will add more every night.

**Comment by swarnabh1990** [comment]
@ra0o0f Great !! Thanks a lot. This will help me a lot for my project. :+1:

**Comment by ra0o0f** [comment]
@swarnabh1990 as i said before im usually around, if you need an example comment here, i will add it asap
