### ISSUE TITLE
Traversal result causes [1205] illegal document handle (while executing)

### ISSUE THREAD

**Issue by JulianMay** [ra0o0f/arangoclient.net#18]
Took some time to find the cultprit, but here it is:

This code 
```
var noteScope = _db.Query()
               .For(a => AQL.Traversal<Target, Relates>(startAt, EdgeDirection.Inbound))
               .For(target => AQL.Edges<Relates>(target.Vertex.Id, EdgeDirection.Inbound))
               .Filter(relation => relation.Label == Relates.NoteAttachementLabel )
               .Return(relation => relation.Out);
```

now (after upgrade to 0.7.2.3) generates this query:

```
for `n` in `Note`  
filter  (  `n`.`_id` in (  
for `target` in  traversal(  `Target` ,  `Relates` ,  "Target/roomstay:1001,1"  ,  "inbound"  )  
for `relation` in  edges(  `Relates` ,  `target`.`Vertex` .`_id`  ,  "inbound"  )  
filter  (  `relation`.`Label`  ==  "Note attached to"  )  
return  `relation`.`_from`  )  
and  (  length(  intersection(  `n`.`Relevances`  ,  ["Check In","Service"]  )  )  >  0  )  )  
return  `n`
```

which throws "[1205] illegal document handle (while executing)" because of "`target`.`Vertex` .`_id`" (which should be "`target`.`vertex` .`_id`", small 'v' in vertex)

**Comment by ra0o0f** [comment]
sorry for the problem, i forgot to change naming convention for `AQLTraversalResult` type which is returned by `AQL.Traversal` method.

i will update nuget package today with this bug fixed, in a mean time you can change naming convention yourself in database setting:

```csharp
db.SharedSetting.Collection.ChangeCollectionPropertyForType<AQLTraversalResult<Target, Relates>>((p) =>
                {
                    p.Naming = NamingConvention.ToCamelCase;
                });
```

by this you can change how properties in collection will be parsed in aql queries

**Comment by JulianMay** [comment]
Cool, thanks

**Comment by ra0o0f** [comment]
i close this issue now, i didn't test your code but if problem wasn't naming convention then comment here again

**Comment by ra0o0f** [comment]
fixed, new nuget packages is available at https://www.nuget.org/packages/ArangoDB.Client
