### ISSUE TITLE
Null ref exception when trying to insert edge to the graph

### ISSUE THREAD

**Issue by drgraduss** [ra0o0f/arangoclient.net#19]
When inserting new edge to the graph null reference exception throw when trying to set edge document ```_from``` and ```_to``` fields in ```DocumentIdentifierModifier.Modify``` method.

Adding these fields to edge document results in a different exception as ```ArangoEdgeDocument.InsertAsync``` adds these fields explicitly to edge document JObject representation

```
var jObject = new DocumentSerializer(db).FromObject(document);
jObject.Add("_from", JToken.FromObject(from));
jObject.Add("_to", JToken.FromObject(to)); 
```

**Comment by ra0o0f** [comment]
@drgraduss i found a bug in resolving `_to` identifier so i upload new dlls in this issue(before publishing new nuget packages). but i'm afraid i didn't understand the exact problem you have:
  
you can insert an edge with `document` object itself, there is no need for `JObject` object, an example would be:

```csharp
    public class Person
    {
        [DocumentProperty(Identifier= IdentifierType.Key)]
        public string Key { get; set; }

        public string Fullname { get; set; }
    }

    public class Friend
    {
        [DocumentProperty(Identifier = IdentifierType.EdgeFrom)]
        public string From { get; set; }

        [DocumentProperty(Identifier = IdentifierType.EdgeTo)]
        public string To { get; set; }

        public string Message { get; set; }
    }

                var p1 = new Person { Fullname = "raoof" };
                var p2 = new Person { Fullname = "drgraduss" };

                db.Insert<Person>(p1);
                db.Insert<Person>(p2);

                var friend = new Friend { Message = "lets be friends" };

                db.InsertEdge<Friend, Person, Person>(p1.Key, p2.Key, friend);

                Debug.Assert(p1.Key != null);
                Debug.Assert(p2.Key != null);
                Debug.Assert(friend.From != null);
                Debug.Assert(friend.To != null);
```

if your problem is something else please provide an example with a failing test

**Comment by ra0o0f** [comment]
download new dlls at http://www.arangoclient.net/arangodb.client.zip

**Comment by drgraduss** [comment]
Hi @ra0o0f. Thanks for quick reply. I was using edge document to create an edge and not a JObject.
JObject snippet is from your code base which is part of InsertEdgeAsync method.

```
graph.InsertEdge<EdgeDocument, VerticeDocument, VerticeDocument>("_from", "_to", new EdgeDocument);
```

I haven't specified ```DocumentProperty``` attributes on Edge document and used plain object.

It would be good to see some documentation as it's not obvious how to map Arango's ```_key, _from, _to, _rev``` properties and if they're required to be present in the document.

**Comment by ra0o0f** [comment]
you can also specify document properties mappings with `DatabaseSharedSetting`

```csharp
// change settings for collections
sharedSetting.Collection.ChangeCollectionPropertyForType<Product>(p =>
                {
                    p.CollectionName = "products";
                    p.Naming = NamingConvention.ToCamelCase;
                });
                
// change default Idetntifier for `_key` property for all types
sharedSetting.Collection.ChangeIdentifierDefaultName(IdentifierType.Key, "Key");

// change default Idetntifier for `_key` property for specific type
sharedSetting.Collection.ChangeDocumentPropertyForType<Product>(p => p.productKey, s => {
                    {
                        s.Identifier = IdentifierType.Key;
                    }});

```

shared settings full example at [DatabaseSetup](https://github.com/ra0o0f/arangoclient.net/blob/next/ArangoDB.Client.Examples/DatabaseSetup.cs)
