### ISSUE TITLE
ArangoDatabase.Query<>().Any() operator throws exception if no elements matching condition found

### ISSUE THREAD

**Issue by drgraduss** [ra0o0f/arangoclient.net#20]
```ArangoDatabase.Query<>().Any()``` operator throws
*sequence contains no matching elements exception*
if no elements matching condition found.

**Comment by ra0o0f** [comment]
@drgraduss its because client doesn't support `Any` and i dont think there is an equivalent operator for `Any` in AQL syntax, but you can achieve it by `Count`

```c#
var count = db.Query().For(_ => new int[] { 1, 2, 3, 4 })
                    .Count(n=>n==4);
``` 

that would translate to 

```sql
return length ((
for `n` in  [1,2,3,4]
filter  (  `n` ==  4  )
return  `n` ))
```

and the client should throw for not supported operations, i am sorry for that

**Comment by drgraduss** [comment]
Thanks for clarification. 

Since ```ArangoDatabase.Query<>()``` supports Linq queries it would be very helpful to know which one supported and which one not. Plus if you're using sub-queries how to construct them as I found by trial and error that it best to use ```ArangoDB.Client.AQL``` functions i.e.

```
var ids = new[] { 1, 2, 3 };

db.Query<User>().Where(x => AQL.In(x.UserId, ids));
```

instead of ```db.Query<User>().Where(x => ids.Contains(x.UserId))```

**Comment by ra0o0f** [comment]
@drgraduss you are absolutely right, unfortunately i can't provide documentation until next month, i am planning to do so(on the http://www.arangoclient.net).

about `ArangoDB.Client.AQL` you are right too, currently only aql functions are the way to act on objects in linq provider, at the future client will support .net equivalent operators like `IList.Contains`.

if you have any other question any time dont hesitate to open an issue for it

**Comment by drgraduss** [comment]
Cheers @ra0o0f!
