### ISSUE TITLE
When creating Graph programmatically Vertex defenition is empty

### ISSUE THREAD

**Issue by drgraduss** [ra0o0f/arangoclient.net#22]
I'm using below command to create arango graph

```
ArangoGraph.Create(new[]
{
	new EdgeDefinitionData
	{
		Collection = "EdgeCollection",
		From = new[] {"User"},
		To = new[] {"User"}
	}
});
```

If I check graph definition in arango web UI vertex collection is empty.

How to specify vertex collection?

**Comment by ra0o0f** [comment]
@drgraduss in web ui `Vertex collections` shows the orphan collections in graph which are not specified in `EdgeDefinition`, click beside `Edge definitions` to see `from` and `to` collections which is `User` here, if you want to specify orphan collections pass it through as third argument

```c#
db.Graph("SocialGraph").Create(new[]
                {
                    new EdgeDefinitionData
                    {
                        Collection = "EdgeCollection",
                        From = new[] {"User"},
                        To = new[] {"User"}
                    }
                },new string[] { "OrphanCollection" });
```
 
![graph](https://cloud.githubusercontent.com/assets/2182530/11247477/7cf80624-8e31-11e5-8ae3-18f250802eea.JPG)

**Comment by drgraduss** [comment]
Thanks!

**Comment by ra0o0f** [comment]
@drgraduss your welcome
