### ISSUE TITLE
Documents filtering by enum value

### ISSUE THREAD

**Issue by drgraduss** [ra0o0f/arangoclient.net#23]
Consider the document below:

```
public class Document
{
    ...
    [JsonConverter(typeof(StringEnumConverter))]
    public MyEnum EnumAttribute { get; set; }
    ...
}

public enum MyEnum
{
    Value1 = 1,
    Value2 = 2
}
```

When this document saved enum value correctly serialized to string.
But when performing query over Document collection and filtering by enum attribute enum serialized to int.

```
db.Query<Document>().Filter(x => x.EnumAttribute == MyEnum.Value1).Update(...)
```

If you explore query data

```
for `x` in `Document`  filter  (  (  `x`.`EnumAttribute`  ==  @P1  ) )  update `x` ...
```
```
@P1 = 1
```

Please advise.

**Comment by ra0o0f** [comment]
@drgraduss it's because `StringEnumConverter` only apply when converting `Document` object not `MyEnum`, see the difference:

```c#
// result will be 1
JsonConvert.SerializeObject(MyEnum.Value1)
// result will be {"EnumAttribute":"Value1"}
JsonConvert.SerializeObject(new Document { EnumAttribute = MyEnum.Value1 })
```

move your `[JsonConverter(typeof(StringEnumConverter))]` attribute on top of enum declartion:

```c#
[JsonConverter(typeof(StringEnumConverter))]
    public enum MyEnum
    {
        Value1 = 1,
        Value2 = 2
    }
```

**Comment by drgraduss** [comment]
Moved ```JsonConverter``` declaration to enum with no luck. Still enum ```@P1``` parameter is int.

**Comment by ra0o0f** [comment]
@drgraduss yes i get same result, it's because relinq(library for parsing linq queries) parse enum to its underlying int values before its convertion by json.net. i should look into it

for now you can prevent it by changing your query to this:
```csharp
db.Query<Document>().Filter(x => x.EnumAttribute == AQL.As<MyEnum>(MyEnum.Value1))
```

**Comment by drgraduss** [comment]
That worked. Thanks!

PS it looks like every time you're using AQL within query you're getting ```InvalidOperationException: Aql functions should only be used in ArangoDatabase.Query``` inside which is caught which affects query construction performance.

Is there a way of pre-compile/cache queries?

**Comment by ra0o0f** [comment]
yes i am aware of exception being thrown, i should be fixed. currently there is no plan for caching/pre- compiling linq queries, but you can always get the translated query data:

```c#
var query = db.Query<Document>().Where(x => x.EnumAttribute == MyEnum.Value1).Select(x => x);

                var queryData = query.GetQueryData();
                // and execute it without need for linq query
                db.CreateStatement<Document>(queryData.Query, queryData.BindVars);
```

**Comment by drgraduss** [comment]
Hey @ra0o0f. I found that you're using custom version of Newtonsoft.Json.

What implications will be if I use standard Newtonsoft.Json instead for documents attributing?

The reason why I need it, I have some model classes in the separate projects that don't have dependency on ArangoDb.Client and I don't want to introduce it.

i.e. my enums used across whole system and are not specific to arango part.

Thanks

**Comment by ra0o0f** [comment]
@drgraduss you should do it by code .if you mean `JsonProperty` attribute i tried to provide a way to define settings for `documents` or `collections` with attributes(declarative way) and code(imperative). you can define your settings by code in a project where `ArangoDB.Client` is referenced. 

```c#
// by attribute
[CollectionProperty(CollectionName = "products")]
public class Product 
{
[DocumentProperty(PropertyName = "price")]
    public decimal Price {get; set;}
}

// by code

sharedSetting.Collection.ChangeCollectionPropertyForType<Product>(c =>
                {
                    c.CollectionName = "products";
                });

sharedSetting.Collection.ChangeDocumentPropertyForType<Product>(c => c.Price, d =>
                   {
                       d.PropertyName = "price";
                   });
```

so there will be no need for `JsonProperty`, unfortunately not all members of `JsonProperty`  are defined so open an issue for what you else need, i will add them asap.

But if you mean custom `JsonConverter` like `StringEnumConverter`, json.net let us add them without attribute usage and i should add a wrapper around it.

let me know if these solve your problem, so i add support for them

**Comment by drgraduss** [comment]
I meant ```JsonConverter``` in my case.

**Comment by ra0o0f** [comment]
@drgraduss ok, i will publish new package in 2 days

**Comment by drgraduss** [comment]
@ra0o0f no problem. thanks a lot!

**Comment by ra0o0f** [comment]
@drgraduss client now has support for custom converters and also a setting for serializing enums, new  packages will be uploaded today

examples:

```c#
// for add new custom converter
sharedSetting.Serialization.Converters.Add(new StringEnumConverter());

// for enabling enum convertion to strings, this just add `StringEnumConverter` under the hood
sharedSetting.Serialization.SerializeEnumAsInteger = false;
```

**Comment by drgraduss** [comment]
@ra0o0f  Thanks!
