### ISSUE TITLE
Upsert?

### ISSUE THREAD

**Issue by JulianMay** [ra0o0f/arangoclient.net#24]
Hey

I was wondering if the UPSERT command will be implemented in the QueryableExtensions? As far as I can see, there is currently no type-safe way to go around with an "update-if-exists,-else-insert" scenario using the arangoclient... I might be wrong(?)

/Julian

**Comment by ra0o0f** [comment]
hi @JulianMay, you are right, currently only way to "update-if-exists,-else-insert" in Arangodb is through  aql upsert command which is not supported now, i will look in to it tomorrow

**Comment by JulianMay** [comment]
Awesome :)

**Comment by ra0o0f** [comment]
@JulianMay client now has support for upsert command, packages will be uploaded today

you can see examples at: https://github.com/ra0o0f/arangoclient.net/blob/next/ArangoDB.Client.Examples/Linq/ModificationQuery.cs

**Comment by JulianMay** [comment]
Very cool. Thanks for the examples, it really helps
