### ISSUE TITLE
Collection index'es?

### ISSUE THREAD

**Issue by JulianMay** [ra0o0f/arangoclient.net#25]
Hello again :3
Just wondering if there is currently, or if there will be, a way to state indexes for collections?
For example **IArangoCollection.EnsureHashIndex(params string[] fields, bool? sparse = default(bool))** and **IArangoCollection.EnsureUniqueConstraint(params string[] fields, bool? sparse = default(bool))** etc.

**Comment by ra0o0f** [comment]
@JulianMay no there isn't currently support for it, there will be for all of the http API, i can tell it wont be in the client earlier than two month

**Comment by JulianMay** [comment]
No biggie - It's no hassle setting them up in javascript API via TransactionData

**Comment by ra0o0f** [comment]
@JulianMay index API is added

```c#
await db.Advanced.EnsureIndexAsync<Customer>(new EnsureIndexData
                {
                    Type = IndexType.Hash,
                    Unique = true,
                    Fields = new List<string> {
                        "cell",
                        // or if you dont want use strings
                        db.SharedSetting.Collection.ResolvePropertyName<Customer>(x=>x.cell)
                    }
                });
```

this is general for all index types, more will be added for each type

**Comment by JulianMay** [comment]
:+1:  !
