### ISSUE TITLE
Two questions: Geters/seters necesarry? And is type byte[] supported in class?

### ISSUE THREAD

**Issue by viliwonka** [ra0o0f/arangoclient.net#30]
Hello! I don't know where else I can ask you this, so I will ask here.

1.Are getters/setters necesary in object definition to use with your ArangoDB plugin?

2. Is byte[] supported in class/model? I am asking, because 

    db.Document<Player>(ID, baseResult = resHandler("getPlayer"))

is giving me exception "Operation is not valid due to the current state of the object". Async version gives me same exception.

Thanks!

**Comment by viliwonka** [comment]
Nevermind, I tested on Windows (previously on Mono), and it works. It's probably Mono bug.

**Comment by ra0o0f** [comment]
@viliwonka for the first question, no there is no rule to use Properties with getter/setter, you can use fields and it should work, if you get an exception please provide a failing test so i can investigate it on mono

for the second question, serializing objects are handled by json.net and for byte arrays it uses `BinaryConverter` ([link to source](https://github.com/danielHalan/Json.NET/blob/master/src/Newtonsoft.Json/Converters/BinaryConverter.cs)) which serialize it to Base64 strings

ArangoDB itself does not support binary storage yet, but i think when it does there will be no byte attributes (json doesn't have binaries), it will be specific binary collections which stores just binary data with some metadata perhaps
