### ISSUE TITLE
Problems using client in dnx project when running on mono

### ISSUE THREAD

**Issue by danludwig** [ra0o0f/arangoclient.net#33]
Just wondering if this is a known issue, or if there are any workarounds. I have a .NET vNext project targeting dnx451, and the client works as expected when running on windows. However when running the same app natively on a mac, I am running into an `InvalidOperationException`:

> Operation is not valid due to the current state of the object

This seems to happen whenever trying to invoke any methods against the API. For example, the following code will throw on the `ListDatabases()` method:

    using (var db = new ArangoDatabase("http://localhost:8529", "_system")) {
      var dbs = db.ListDatabases();
    }

...however other method invocations result in the same exception & message. If you need to see a full stacktrace please let me know. In the meantime, here is a brief one:

    Unhandled Exception:
    System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
      at System.Net.Http.HttpClientHandler.set_Proxy (IWebProxy value) <0x10a5c3ce0 + 0x0008c> in <filename unknown>:0
      at ArangoDB.Client.Http.HttpConnection+<>c.<.cctor>b__10_0 () <0x10a5c3830 + 0x000eb> in <filename unknown>:0
      at System.Lazy1[T].CreateValue () <0x104f87bf0 + 0x00174> in <filename unknown>:0
    --- End of stack trace from previous location where exception was thrown ---

There are other sections where it looks like the exception was wrapped and rethrown by the task awaiter, but here are the relevant lines from the Arango client lib:

    at ArangoDB.Client.Http.HttpCommand+<SendCommandAsync>d__33.MoveNext () <0x10a5bac50 + 0x002ab> in <filename unknown>:0
    ...
    at ArangoDB.Client.Http.HttpCommand+<RequestGenericListResult>+d__29`2[TResult.TDeserialize].MoveNext () <0x10a5b9bc0 + 0x002ac> in <filename unknown>:0
    ...
    at ArangoDB.Client.ArangoDatabase<ListDatabasesAsync>d__50.MoveNext () <0x10a5b78f0 + 0x002b0> in <filename unknown>:0

**Comment by ra0o0f** [comment]
@danludwig i think this is the same problem that client didn't work on mono too, it is solved now in source code but the nuget packages are not updated, can you compile it yourself? or wait a couple of hours till i update nuget packages

**Comment by danludwig** [comment]
Of course I can wait a couple of hours, but I do need to have the nuget packages if I want to continue using your client (which I like because of the LINQ provider :). I am creating a "Getting Started with..." project, so people who clone my repo will need to `dnu restore` to get your client package (meaning, of course, they must be in nuget). Thank you!

**Comment by ra0o0f** [comment]
@danludwig great, is this the project https://github.com/danludwig/eventsourced.net?

**Comment by danludwig** [comment]
@ra0o0f yes, it is. My employer is giving us a 3 week sprint to investigate a project of our own choosing, and this is what I am doing for that sprint. I chose Arango because it seemed fairly straightforward to install & set up, though I have never used it before. I am used to RavenDB, but that won't run on a mac, and couch didn't seem to do document collections the way I wanted.

**Comment by ra0o0f** [comment]
@danludwig new packages are updated, version 0.7.2.9
thanks for choosing this client

**Comment by danludwig** [comment]
Yes, yes yes! No more exceptions in dnx mono, the app works the same as it does on windows. Thanks & praise.

In the meantime I began to investigate what it would take to use the other popular arango client (which was working on mono), and it was just terrible. It wanted all of my document properties to have setters, I couldn't use interface types on properties like `IList<T>`, and of course there was no LINQ. I do have one other issue I was running into with your client, but I am going to check and make sure I can still reproduce it after this version bump before I bug you about it. Thanks again @ra0o0f!
