### ISSUE TITLE
OutOfMemoryException when enumerating over documents due to DocumentTracker

### ISSUE THREAD

**Issue by shift-evgeny** [ra0o0f/arangoclient.net#41]
ArangoDB 2.8.2 on Windows 7 x64. When I try to iterate over all documents in a collection of just under 10M documents (14 columns per document) the my program uses a lot of memory and ultimately crashes with OutOfMemoryException, even though I don't keep the loaded objects. Code:

```
            using (var db = new ArangoDatabase("http://localhost:8529", "Jabba"))
            {
                var entities = db.Collection("Entities");
                var cursor = entities.All<Entities>(limit: 1000000, batchSize: 1000);

                foreach (var value in cursor.AsEnumerable())
                {
					// Do some stuff
                }
            }
```

Profiling shows that the DocumentTracker tracker appears to be keeping all loaded objects in memory. If I replace it with a stub (FakeDocumentTracker) this problem goes away.

I'm not sure what DocumentTracker is supposed to do, but please provide a way to disable it. Perhaps it should even be disabled by default, given this problem.

**Comment by shift-evgeny** [comment]
[FakeDocumentTracker.cs.txt](https://github.com/ra0o0f/arangoclient.net/files/131051/FakeDocumentTracker.cs.txt)

**Comment by ra0o0f** [comment]
@shift-evgeny i forgot to tell you that you should disable change tracking for this operation: there is no need for the stub, you can do this by:

```c#
sharedSetting.DisableChangeTracking = true;
// or
db.Setting.DisableChangeTracking = true;
```

**Comment by ra0o0f** [comment]
@shift-evgeny as @dothebart said this could be a cheaper operation using the http export api, if you need this i can add it to the client in next release

**Comment by shift-evgeny** [comment]
Thanks, that looks like exactly what I'm looking for, but is there a singleton instance of SharedSetting somewhere? Or should I use
```
db.SharedSetting.DisableChangeTracking = true;
```
?

**Comment by shift-evgeny** [comment]
I don't understand ArangoDB enough to be sure, but it sounds like the export API does exactly what IArangoCollection.All() needs. So it would help in this case, but like I said in https://github.com/arangodb/arangodb/issues/1740#issuecomment-184310584 it might not help in other cases.

**Comment by ra0o0f** [comment]
@shift-evgeny for creating a `DatabaseSharedSetting` object look at the 

http://www.arangoclient.net/Document/ArangoDatabase

and 

http://www.arangoclient.net/Document/DatabaseSetting

**Comment by ra0o0f** [comment]
@shift-evgeny `ArangoCollection.All` would fetch all result set in ArangoDB server memory, that's why it gets timeout(if the timeout is set). look at https://www.arangodb.com/faq/ `Cursors in ArangoDB vs. cursors in MongoDB` section

but i think export api would not guarantee things you read at link above and send the result without storing it in memory

**Comment by shift-evgeny** [comment]
OK, thanks, DisableChangeTracking=true fixes the memory issue.

Thanks for the FAQ link. Looks like it would be difficult to use ArangoDB the way I was hoping to...
