### ISSUE TITLE
Dotnet Core support?

### ISSUE THREAD

**Issue by eswann** [ra0o0f/arangoclient.net#48]
Are there plans to make the client dotnet core compatible?

**Comment by ra0o0f** [comment]
@eswann sorry for the delayed response. yes i will add specific release for the dotnet right after i update client so it can work with version 3.0 ArangoDB(currently client has many breaking changes on ArangoDB 3.0 that should be fixed, and it may take a month).

**Comment by kwrang** [comment]
@ra0o0f do you have an ETA for this?

**Comment by ra0o0f** [comment]
@kwrang yes, earlier next month

**Comment by ra0o0f** [comment]
@eswann  @kwrang client now supports .NET Core, install the latest version from nuget

**Comment by kwrang** [comment]
awesome. thanks @ra0o0f
