### ISSUE TITLE
Why Newtonsoft.Json package is copy-pasted instead of dependency?

### ISSUE THREAD

**Issue by OutSorcerer** [ra0o0f/arangoclient.net#49]
Even if new version of Newtonsoft.Json introduces breaking changes it could be implemented as package dependency.
That shouldn't be an issue as Newtonsoft.Json is quite stable.
And because it is very popular many .NET projects already have references to it. So it causes duplication and it is also impossible to use existing `JsonConverter`s both for normal and copy-pasted Newtonsoft.Json.
Are there some problems behind current decision? I or someone else could contribute to solving them.

**Comment by ra0o0f** [comment]
@OutSorcerer you are right json.net has all settings that i needed. i was about to adding the Newtonsoft.Json as a dependency in next release.

**Comment by ra0o0f** [comment]
@OutSorcerer embeded json.net is now removed from the client, install the latest version from nuget

**Comment by OutSorcerer** [comment]
@ra0o0f Thanks for the feedback and for all the great work on this package.
