### ISSUE TITLE
Cannot create new Edge

### ISSUE THREAD

**Issue by PavelPikat** [ra0o0f/arangoclient.net#50]
I've been testing this driver and made a sample app, where I defined my models. Then I tried to execute this code: 
`await _db.InsertEdgeAsync<HAS_PROFILE, UserAccount, UserProfile>(userAccount.Id, userProfile.Id, new HAS_PROFILE());`

But got 
> unknown path '/_api/edge?collection=HAS_PROFILE&createCollection=True&waitForSync=False&from=UserAccounts%2F617261&to=UserProfiles%2F617265'. ErrorNumber: 404 HttpStatusCode: 404

Is it possible to create edges with this driver? If so, how it supposed to be done? I could not find any documentation on GitHub or examples\tests in the source

**Comment by ra0o0f** [comment]
@PavelPikat unfortunately driver does not support ArangoDB v3, the support will be added in next month

**Comment by ra0o0f** [comment]
@PavelPikat driver now supports v3.0 version of ArangoDB. install it from nuget 

but as http api is changed, for inserting an edge you should do:

```c#
await _db.InsertEdgeAsync<HAS_PROFILE>(new HAS_PROFILE());
```

`from` and `to` edge members should now be the members of `HAS_PROFILE` object

**Comment by PavelPikat** [comment]
@ra0o0f Thanks for the update

There are no InsertEdge or InsertEdgeAsync methods in the library anymore. 
Did you mean that we have to use regular InsertAsync<T> and create the Edge as a regular document in edge collection?

**Comment by kwrang** [comment]
@PavelPikat its on IArangoGraph:
check out the graph examples: https://github.com/ra0o0f/arangoclient.net/blob/next/src/ArangoDB.Client.Examples/Graphs/GraphCommand.cs

**Comment by ra0o0f** [comment]
@PavelPikat sorry i updated the previous answer with the correct syntax.

`IArangoDatabase.InsertEdge` is removed from the API, so to insert edges you should do it like general documents: as ArangoDB docs says `Working with Edge: Use the general document REST api for create/read/update/delete.` in https://docs.arangodb.com/3.0/HTTP/Edge/WorkingWithEdges.html

You can insert edges/vertices with graph API or directly insert them with `IArangoDatabase.Insert` method. graph API will give you `EdgeDefenitions` which ensure integrity for which edge/vertex collections are used.

in ArangoDB docs : https://docs.arangodb.com/3.0/Manual/Graphs/index.html
```
When to choose anonymous or named graphs?

As noted above, named graphs ensure graph integrity, both when inserting or removing edges or
vertices. So you won't encounter dangling edges, even if you use the same vertex collection
in several named graphs. This involves more operations inside the database which don't come
for free.Thereforeanonymous graphs may be faster in many operations. So this question boils
down to 'Can I afford the additional effort or do I need the warranty for integrity?'.
```
