### ISSUE TITLE
How to execute pure AQL queries?

### ISSUE THREAD

**Issue by PavelPikat** [ra0o0f/arangoclient.net#51]
I am new to ArangoDB and I find it hard to write complex queries with LINQ, and would like to execute queries in clean AQL. 
How can it be done within this library?

For example, I want to retrieve all articles that belong to groups current user is member of. 
My LINQ query looks like 
```c#
var query = from p in db.Query<Person>()
                where p.Name == "Bob"
                from g in db.Query<Group>()
                from memberOf in db.Query<MEMBER_OF>()
                where memberOf.Person == p.Id
                where g.Id == memberOf.Group
                from a in db.Query<Article>()
                from childOf in db.Query<CHILD_OF>()
                where childOf.Child == a.Id && childOf.Parent == g.Id
                select a;
```

And my AQL looks like:

```
FOR u IN People FILTER u.Name == "Bob"
    FOR g IN OUTBOUND u MEMBER_OF
        FOR a IN INBOUND g CHILD_OF RETURN a
```

**Comment by kwrang** [comment]
try db.CreateStatement<T>

**Comment by PavelPikat** [comment]
@kwrang Great example! Thank you very much, it works like a charm! :+1:

**Comment by ra0o0f** [comment]
@PavelPikat i'm planning to add AQL `OUTBOUND` and `INBOUND` keywords for LINQ in [v3.0 branch](https://github.com/ra0o0f/arangoclient.net/tree/v3.0) this month.

**Comment by ra0o0f** [comment]
@PavelPikat graph traversal in LINQ is now supported

AQL traversal doc https://docs.arangodb.com/3.0/AQL/Graphs/index.html

LINQ traversal examples https://github.com/ra0o0f/arangoclient.net/blob/next/src/ArangoDB.Client.Examples/Linq/TraversalQuery.cs

see if you can write you query in AQL with new graph traversal syntax
