### ISSUE TITLE
JsonProperty attribute is ignored in 0.7.4

### ISSUE THREAD

**Issue by PavelPikat** [ra0o0f/arangoclient.net#52]
I declare my models with JsonProperty attribute like this:

```c#
[JsonProperty(NullValueHandling = NullValueHandling.Ignore, DefaultValueHandling = DefaultValueHandling.Ignore)]
public bool? SomeVariable {get; set; }
```

It worked fine prior 0.7.4 - documents created in the database didn't have fields with nulls.
But now all of the fields are created in the database, even if the value is null. It seems like these JsonProperty attributes are ignored.

I tried it with `bool?` and `string` and it doesn't work. But it does work with `List<T>` though

**Comment by ra0o0f** [comment]
@PavelPikat use `Newtonsoft.Json.JsonPropertyAttribute` instead of `ArangoDB.Client.Common.Newtonsoft.Json.JsonPropertyAttribute`

Its because embedded json.net is not being used for the serialization anymore

**Comment by ra0o0f** [comment]
@PavelPikat i refactored namespace of the embedded json.net so others that has used the embedded attributes get the compile error.

install latest version from nuget

**Comment by PavelPikat** [comment]
@ra0o0f Thanks for quick response. It works now.
