### ISSUE TITLE
Upsert always insert

### ISSUE THREAD

**Issue by redplane** [ra0o0f/arangoclient.net#53]
Hi,
I'm using the driver with arangodb 3.0
I use this code to upsert my data:

```
           var insert = new Account
            {
                Email = "email01@gmail.com",
                FirstName = "Adam",
                LastName = "Smith"
            };

            var update = new Account
            {
                Email = "email01@gmail.com",
                FirstName = "John",
                LastName = "Peterson"
            };

            using (var arangoDatabase = new ArangoDatabase(new DatabaseSharedSetting()
            {
                Url = "http://127.0.0.1:8529/",
                Database = "_system",
                Credential = new NetworkCredential()
                {
                    UserName = "root",
                    Password = "xxxxxkkkk"
                }
            }))
            {
                arangoDatabase.Query()
                    .Upsert(_ => new Account() {Email = insert.Email},
                        _ => insert, ((aql, x) => update))
                        .In<Account>()
                        .Execute();
            }
```

If "email01@gmail.com" doesn't exist. It will be inserted, that's OK.
But next time, as "email01@gmail.com" exists, it throws me an exception: **unique constraint violated (while executing). ErrorNumber: 1210 HttpStatusCode: 409**

Can you help me to solve this problem please ?
Thank you,

**Comment by ra0o0f** [comment]
@redplane problem could be upsert search expression:

`new Account() {Email = insert.Email}`
 serialize to 
`{ Email: "email01@gmail.com", FirstName: null, LastName: null }`

Since this expression will be never found, then insert will occur and you get `unique constraint violated` because you have unique hash index on `Email`

One solution is to ignore null members by:

```csharp
        public class Account
        {
            public string Email { get; set; }

            [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
            public string LastName { get; set; }

            [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
            public string FirstName { get; set; }
        }
```

Another solution is to use an anonymous object for search expression:

```csharp
arangoDatabase.Query()
                    .Upsert(_ => new Account() {Email = insert.Email}

// should be

arangoDatabase.Query()
                    .Upsert(_ => new {Email = insert.Email}
```

**Comment by redplane** [comment]
Sorry, I forgot importing my model class. Here it is :

`public class Account
    {
        [DocumentProperty(Identifier = IdentifierType.Key)]
        public string Email { get; set; }

        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public string FirstName { get; set; }

        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public string LastName { get; set; }
    }`

By the way, I used anonymous object as your guide, but still failed
http://i.imgur.com/D0jw7I3.png

**Comment by ra0o0f** [comment]
@redplane do you use `ArangoDB.Client.Common.EmbeddedNewtonsoft.Json.JsonProperty` attribute on class members? if yes you should use `Newtonsoft.Json.JsonProperty`.

**Comment by redplane** [comment]
The second solution worked :)

`arangoDatabase.Query()
                    .Upsert(_ => new { _key = insert.Email }`

I think you should change the example code of Linq folder, because I copied code from that example :)
Thank you for your help :). I think this issue can be closed.

**Comment by ra0o0f** [comment]
@redplane first solution should work too, sorry but could you check if you use ArangoDB.Client.Common.EmbeddedNewtonsoft.Json.JsonProperty attribute on class members?

**Comment by redplane** [comment]
After checking these 2 solutions you gave me. Here is my conclusion:
- The first one works when no key is specified in my Model. That means my model should be:

`/// <summary>
        /// Account email.
        /// </summary>
        public string Email { get; set; }

        /// <summary>
        /// Account first name.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public string FirstName { get; set; }

        /// <summary>
        /// Account last name.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public string LastName { get; set; }`

And the function I'll use for upsert is : 
`arangoDatabase.Query()
                    .Upsert(_ => new Account() {Email = insert.Email}`

- The second one works when I set a property as a key in my model. Here is my model in this case:

`public class Account
    {
        /// <summary>
        /// Account email.
        /// </summary>
        [DocumentProperty(Identifier = IdentifierType.Key)]
        public string Email { get; set; }

        /// <summary>
        /// Account first name.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public string FirstName { get; set; }

        /// <summary>
        /// Account last name.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public string LastName { get; set; }
        
    }`

And the upsert function I used was : 
`arangoDatabase.Query() .Upsert(_ => new { _key = insert.Email }`

Thank you for these solutions :). You saved my day.

**Comment by ra0o0f** [comment]
@redplane your welcome, first solution should work too, i tested it my self, can you provide a failing test please?

**Comment by redplane** [comment]
I tested my app again, the 1st solution worked :D.
