### ISSUE TITLE
DistinctBy feature.

### ISSUE THREAD

**Issue by ximbor** [ra0o0f/arangoclient.net#54]
Hi,
is available a DistinctBy feature in order to get a list of objects, but distincted by some properties,
or can i get this by grouping objects by all their atreibutes and taking the first object for each group?

Thank you.

**Comment by ra0o0f** [comment]
@ximbor [`DISTINCT`](https://www.arangodb.com/2015/07/return-distinct-in-aql/) keyword is supported in ArangoDB but not in the client yet. I am working on client LINQ provider at the moment and i will add support for `DISTINCT`. In the mean time you can use `GroupBy(Collect in AQL)` for making the result-set unique

**Comment by ra0o0f** [comment]
@ximbor `distinct` is now supported by client. get the latest version from nuget

**Comment by smust** [comment]
do you have any example for group by ?
