### ISSUE TITLE
How can I create composite key?

### ISSUE THREAD

**Issue by sithwin** [ra0o0f/arangoclient.net#58]
I have a resource class and would like to create composite key as below:

`public class Resource
{
	[Key, Column(Order = 1)]
	public Guid ResourceId {get; set;}
	[Key, Column(Order = 2)]
	[MaxLength(5)]
	public string Locale {get; set;}
	public string ResourceName {get; set;}
}`

**Comment by ra0o0f** [comment]
ArangoDB key can only be set on one attribute named _key. with c# client you can only specify which one of class members should be translate to _key attribute.

@sithwin  ResourceId type is Guid which is already unique itself, why you want to combine it with Locale?

I didn't do this myself but you can concat ResourceId and Locale and set it to Key(just be aware keys should be at most 254 bytes long)

```public string Key => $"{ResourceId.ToString("N")}_{Locale}";```
Or if you want these fields to be unique for each document, you can create a unique hash index on ResourceId and Locale and behave them as normal attributes.
