### ISSUE TITLE
Scalar-Value Function

### ISSUE THREAD

**Issue by sithwin** [ra0o0f/arangoclient.net#59]
Is there any method to return as Scalar Value?

for example: I would like to check the data is exist. Now I am checking as:

`if (_arangoDb.Document<Resource>(Id) == null)`

But it returns the whole object.
Is there any better way?

Thanks.

**Comment by ra0o0f** [comment]
@sithwin if by Scalar you mean to return attributes of a document then you should use LINQ for this:

Assume you want to return `ResourceName` attribute of `Resource` collection:

```c#
string resourceName = db.Query<Resource>()
               // with Where you could apply any condition
                .Select(r => r.ResourceName)
                .First();
``` 

If you want to check if a document has a attribute or not you could:

```c#
bool hasResourceName = db.Query<Resource>()
                .Select(r => AQL.Has(r, "ResourceName"))
                .First();
```

**Comment by sithwin** [comment]
Hi @ra0o0f , thanks for your quick reply.

Any performance different between:

                `bool has = _arangoDb.Query<CmsContentTypeView>()
                    .Where( r => r.Key == Id.ToString())
                    .Select(r => AQL.Has(r, "Id"))
                    .First();`

And

`if (_arangoDb.Document<Resource>(Id) == null)`

I think, first query returns only Id and Second has whole object.

Please advice!

Thanks.

**Comment by ra0o0f** [comment]
@sithwin first query doe not return the id, it checks if document has `Id` attribute or not. if you want to return it use:

```c#
string resourceName = db.Query<CmsContentTypeView>()
                .Where( r => r.Key == Id.ToString())
                .Select(r => r.Key)
                .First();
```

About the performance you are right, `_arangoDb.Document` will return the whole object and therefore it's slower.

@sithwin i'm not sure if i understand completely what you want to achieve, if  you can explain it, i can show how to query it

**Comment by sithwin** [comment]
Hi @ra0o0f ,

Firstly, I would like to make use of arangoDB key for better performance.
Secondly, I just want to check the again whether the data is successfully inserted. On the other hand, I created custom arrangoDb key before I inserted into database.

Right now, I used  
`if (_arangoDb.Document<Resource>(Id) == null)` to check the data is inserted or not. However, it returns the whole object. It is expensive.

I just want to check with the key whether it is exist or not..

I think, this is less expensive than my above "if" statement.
`string resourceName = db.Query<CmsContentTypeView>()
                .Where( r => r.Key == Id.ToString())
                .Select(r => r.Key)
                .First();`

Please advice what should be the best approach.

Thanks.

**Comment by ra0o0f** [comment]
@sithwin now i understand what you want to do.

for checking if a document exists or not with LINQ(AQL), there is no need for `AQL.Has` since it checks for attributes existence not the document, just get count and check if its zero or not

```c#
var count = db.Query<Resource>()
                   .Where(r => r.Key == Id.ToString())
                    .Count();

if(count!=0)
  // then exists
```

There is another way to check for the document existence without loading it. it's not implemented yet. i will inform you as soon as its done

@sithwin note that ArangoDB has also `Upsert` command which can insert/update a document if it exists or not in one request. this is usefull if you care about performance and consistency

**Comment by sithwin** [comment]
Hi @ra0o0f , 

For now on, `.Count()` can be solved my requirement. 

Pls be inform once document existence method is available.

Thanks a lot!
