### ISSUE TITLE
How to create Readonly property?

### ISSUE THREAD

**Issue by sithwin** [ra0o0f/arangoclient.net#60]
Hi, 

I'm trying to create readonly property in my Class:

```
public class Person
    {
        public string Key { get; set; }
        public string FirstName { get; set; }
        public string  LastName { get; set; }
        public string  DisplayName { get { return FirstName + " " + LastName; } }
    }
```

But DisplayName is created in the ArangoDb. Please advice!

Thanks!

**Comment by ra0o0f** [comment]
If you mean ignoring `DisplayName` for persistence, use `DocumentProperty` attribute:

```c#
    public class Person
    {
        public string Key { get; set; }
        public string FirstName { get; set; }
        public string  LastName { get; set; }

        [DocumentProperty(IgnoreProperty = true)]
        public string  DisplayName { get { return FirstName + " " + LastName; } }
    }
```

**Comment by sithwin** [comment]
Hi @ra0o0f, 

Exactly!! 
Could you tell me where can I read those usage documentation since I couldn't [here](https://github.com/ra0o0f/arangoclient.net/blob/next/docs/tutorial/csharp-in-10-minutes.md).

 Thanks a lot!

**Comment by ra0o0f** [comment]
@sithwin usage documentation is not complete yet, it will be soon.

**Comment by sithwin** [comment]
Hi @ra0o0f,
pls inform me when it is out!
Thanks!
