### ISSUE TITLE
Cannot read documents with '+' character in the ID

### ISSUE THREAD

**Issue by richorama** [ra0o0f/arangoclient.net#71]
I seem to be able to write a document with a '+' in the ID, but not read.

The '+' is permitted.

**Comment by ra0o0f** [comment]
@richorama sorry for the delay, i tested inserting  a document with '+' in it. it works for me, could you provide a failing test?

```c#
public class Person
    {
        [DocumentProperty(Identifier = IdentifierType.Key)]
        public string Key { get; set; }

        public string Title { get; set; }
    }

db.Insert<Person>(new Person
                {
                    Key = "bv+zz",
                    Title = "z"
                });
```

**Comment by richorama** [comment]
My attempts to reproduce so far have failed, although it breaks consistently in my app :¬/

I'll keep trying...

**Comment by richorama** [comment]
Thanks!
