### ISSUE TITLE
VelocyStream network protocol

### ISSUE THREAD

**Issue by agrothe** [ra0o0f/arangoclient.net#73]
Are there any plans to implement the VelocyStream network protocol as opposed to just the HTTP connections?

**Comment by ra0o0f** [comment]
@agrothe yes, currently the serializer is implemented in another https://github.com/ra0o0f/velocypack.net , i will include it in client soon

**Comment by agrothe** [comment]
That is good news! As I start using the library I will try and help out with further usage examples. Long term though, the TCP connection via Velocy is vital to long term success, IMHO.
