### ISSUE TITLE
Readme file duplicated (Windows)

### ISSUE THREAD

**Issue by jjchiw** [ra0o0f/arangoclient.net#8]
There are two Readme.md files in the repository

- https://github.com/ra0o0f/arangoclient.net/blob/master/README.md
- https://github.com/ra0o0f/arangoclient.net/blob/master/readme.md

In windows is kinda of difficult to work with files with the same name, since windows file system is case insensitive and when I'm trying to commit to git it's always appears as it has been modifed, can we delete one?

thanks

**Comment by ra0o0f** [comment]
thanks, README.md doenst have duplicate now
