### ISSUE TITLE
How to use AQL without concrete types

### ISSUE THREAD

**Issue by jeff-pang** [ra0o0f/arangoclient.net#90]
Also, how do you use Linq query without concrete types? For example I have

```
FOR s IN [{...}, {...}] INSERT s IN Schedules
```

but I don't have a concrete class which is named `Schedule`, how do I write a fluent (Linq) expression?

**Comment by ra0o0f** [comment]
@jeff-pang for removing documents:

```c#
var removedDoc = db.Query<movies>()
                    .Where(x => x.Key == "43019436")
                    .Remove()
                    .First();
```

currently there is no way to write LINQ without  concrete types, you should use `db.CreateStatement` to write dynamic queries.

you had a complex query. i may be help to write it in LINQ for you

**Comment by jeff-pang** [comment]
@ra0o0f can I run AQL without concrete types using `db.CreateStatement`? I tried `db.CreateStatement(aql, bindVars);` but this will give compile error

**Comment by ra0o0f** [comment]
@jeff-pang sorry for late response, what is the query?

**Comment by jeff-pang** [comment]
@ra0o0f its ok. Thanks for replying, but I have moved on so I can't quite remember the query and use case anymore. I will close this issue. Thanks anyway
